# Generated by Django 5.0.4 on 2024-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
