# Generated by Django 5.0.4 on 2024-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="activation_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
