# Generated by Django 5.0.4 on 2024-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
