# Generated by Django 5.0.4 on 2024-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification_is_read_notification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("posts", "Posts"),
                    ("articles", "Articles"),
                    ("communities", "Communities"),
                    ("users", "Users"),
                ],
                default="communities",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
