# Generated by Django 5.0.4 on 2024-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification_category_notification_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request_sent", "Join Request Sent"),
                    ("join_request_received", "Join Request Received"),
                    ("article_commented", "Article Commented"),
                    ("post_replied", "Post Replied"),
                    ("comment_replied", "Comment Replied"),
                    ("article_submitted", "Article Submitted"),
                ],
                max_length=30,
            ),
        ),
    ]
