# Generated by Django 5.0.4 on 2024-06-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_created_at_article_updated_at"),
        ("communities", "0005_community_rules"),
        ("users", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="communities.community",
            ),
        ),
    ]
