# Generated by Django 5.0.6 on 2024-07-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0007_hashtag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hashtag",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="hashtag",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="hashtag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="hashtag",
            name="object_id",
        ),
        migrations.CreateModel(
            name="HashtagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.hashtag"
                    ),
                ),
            ],
            options={
                "unique_together": {("hashtag", "content_type", "object_id")},
            },
        ),
    ]
