# Generated by Django 5.0.4 on 2024-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_hashtag_unique_together_alter_hashtag_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_notify",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="institute",
        ),
        migrations.AddField(
            model_name="user",
            name="academic_statuses",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="home_page_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
    ]
