# Generated by Django 5.0.6 on 2024-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_notification_post_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request_sent", "Join Request Sent"),
                    ("join_request_received", "Join Request Received"),
                    ("article_commented", "Article Commented"),
                    ("post_replied", "Post Replied"),
                    ("comment_replied", "Comment Replied"),
                    ("article_submitted", "Article Submitted"),
                    ("article_assigned", "Article Assigned"),
                ],
                max_length=30,
            ),
        ),
    ]
