# Generated by Django 5.1.4 on 2025-05-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_hashtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.FileField(null=True, upload_to='profile_images/local/'),
        ),
    ]
