# Generated by Django 5.1.4 on 2025-05-10 21:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.FileField(null=True, upload_to=users.models.User.get_upload_path),
        ),
    ]
