# Generated by Django 5.2.3 on 2025-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0015_alter_user_profile_pic_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "content_type", "-created_at"],
                name="bookmark_user_type_created",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="bookmark_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="bookmark_user_type_obj",
            ),
        ),
    ]
