# Generated by Django 5.2.3 on 2026-01-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_bookmark_options_alter_bookmark_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(db_index=True, max_length=100)),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_setting",
                "indexes": [
                    models.Index(
                        fields=["user", "config_name"], name="user_setting_lookup"
                    )
                ],
                "unique_together": {("user", "config_name")},
            },
        ),
    ]
