# Generated by Django 5.2.3 on 2026-02-28 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_usersetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        db_index=True,
                        help_text="S3 object key (path), e.g., user-attachments/prod/filename.jpg",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME type of the uploaded image", max_length=50
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "ref_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Reference count - number of times this image is used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_image",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ref_count", "created_at"],
                        name="uploaded_image_cleanup_idx",
                    )
                ],
            },
        ),
    ]
