# Generated by Django 5.2.12 on 2026-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_uploadedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="post",
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("articles", "Articles"),
                    ("communities", "Communities"),
                    ("users", "Users"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request_received", "Join Request Received"),
                    ("join_request_approved", "Join Request Approved"),
                    ("join_request_rejected", "Join Request Rejected"),
                    ("invitation_received", "Invitation Received"),
                    ("invitation_responded", "Invitation Responded"),
                    ("article_submitted", "Article Submitted"),
                    ("article_assigned", "Article Assigned"),
                    ("article_accepted", "Article Accepted"),
                    ("article_rejected", "Article Rejected"),
                    ("review_submitted", "Review Submitted"),
                    ("review_comment", "Review Comment"),
                    ("discussion_created", "Discussion Created"),
                    ("discussion_comment", "Discussion Comment"),
                    ("discussion_mention", "Discussion Mention"),
                ],
                max_length=30,
            ),
        ),
    ]
