# Generated by Codex on 2026-07-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_notification_post_alter_notification_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionAuthCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_id", models.CharField(db_index=True, max_length=100)),
                ("code_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("code_challenge", models.CharField(max_length=128)),
                ("code_challenge_method", models.CharField(default="S256", max_length=10)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("state", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_auth_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extension_auth_code",
            },
        ),
        migrations.AddIndex(
            model_name="extensionauthcode",
            index=models.Index(fields=["client_id", "expires_at"], name="ext_auth_client_expiry"),
        ),
        migrations.AddIndex(
            model_name="extensionauthcode",
            index=models.Index(fields=["user", "-created_at"], name="ext_auth_user_created"),
        ),
    ]
