# Generated by Django 5.0.4 on 2024-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_community_profile_pic_url_community_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="cited_article",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="community",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="accepted",
        ),
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="CommunityComment",
        ),
        migrations.DeleteModel(
            name="CommunityPost",
        ),
    ]
