# Generated by Django 5.0.4 on 2024-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0004_community_banner_pic_url_alter_invitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="rules",
            field=models.JSONField(default=list),
        ),
    ]
