# Generated by Django 5.0.4 on 2024-07-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_rename_user_reviewcomment_author_and_more"),
        ("communities", "0005_community_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved by Admin"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.community",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleSubmissionAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_moderator", models.BooleanField(default=False)),
                ("approved", models.BooleanField(null=True)),
                ("comments", models.TextField(blank=True)),
                ("assessed_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "community_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="communities.communityarticle",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="articlesubmissionassessment",
            constraint=models.UniqueConstraint(
                fields=("community_article", "assessor"), name="unique_article_assessor"
            ),
        ),
    ]
