# Generated by Django 5.0.6 on 2024-07-16 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0006_communityarticle_articlesubmissionassessment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="tags",
        ),
    ]
