# Generated by Django 5.0.7 on 2024-08-08 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0008_community_about"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communityarticle",
            name="assigned_moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_moderations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communityarticle",
            name="assigned_reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ArticleSubmissionAssessment",
        ),
    ]
