# Generated by Django 5.1.4 on 2025-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_communityarticle_assigned_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_pseudonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='requires_admin_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
