# Generated by Django 5.1.4 on 2025-02-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_community_is_pseudonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_settings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
