# Generated by Django 5.1.4 on 2025-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_community_community_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='is_pseudonymous',
        ),
        migrations.AddField(
            model_name='communityarticle',
            name='is_psuedonymous',
            field=models.BooleanField(default=False),
        ),
    ]
