# Generated by Django 5.1.4 on 2025-03-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_remove_community_is_pseudonymous_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityarticle',
            old_name='is_psuedonymous',
            new_name='is_pseudonymous',
        ),
    ]
