# Generated by Django 5.1.4 on 2025-04-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_created_at_alter_review_created_at_and_more'),
        ('communities', '0013_rename_is_psuedonymous_communityarticle_is_pseudonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityarticle',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved by Admin'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityarticle',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='communityarticle',
            index=models.Index(fields=['article', 'community'], name='communities_article_98e4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='communityarticle',
            index=models.Index(fields=['community', 'status'], name='communities_communi_0af2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='communityarticle',
            index=models.Index(fields=['status'], name='communities_status_aa3854_idx'),
        ),
    ]
