# Generated by Django 5.1.4 on 2025-05-10 21:51

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_alter_community_banner_pic_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner_pic_url',
            field=models.FileField(null=True, upload_to=communities.models.Community.get_upload_path),
        ),
        migrations.AlterField(
            model_name='community',
            name='profile_pic_url',
            field=models.FileField(null=True, upload_to=communities.models.Community.get_upload_path),
        ),
    ]
