# Generated by Django 5.2.3 on 2025-12-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0016_alter_community_banner_pic_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityarticle",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved by Admin"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("unpublished", "Unpublished"),
                ],
                db_index=True,
                default="submitted",
                max_length=20,
            ),
        ),
    ]
