# Generated by Django 5.0.4 on 2024-06-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_community_article_published_article_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="article_image_url",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="pdf_file",
            new_name="article_pdf_file_url",
        ),
    ]
