# Generated by Django 5.0.4 on 2024-06-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_created_at_article_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="faqs",
            field=models.JSONField(default=list),
        ),
    ]
