# Generated by Django 5.0.4 on 2024-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_reviewcomment_delete_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewcomment",
            old_name="user",
            new_name="author",
        ),
        migrations.AddField(
            model_name="reviewcomment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
