# Generated by Django 5.0.6 on 2024-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_review_community_reviewcomment_community_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlepdf",
            old_name="file",
            new_name="pdf_file_url",
        ),
    ]
