# Generated by Django 5.0.6 on 2024-07-16 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0012_rename_file_articlepdf_pdf_file_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="article_pdf_file_url",
        ),
        migrations.RemoveField(
            model_name="article",
            name="community",
        ),
        migrations.RemoveField(
            model_name="article",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="article",
            name="published",
        ),
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
    ]
