# Generated by Django 5.0.7 on 2024-07-18 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_article_article_pdf_file_url_and_more'),
        ('communities', '0007_remove_community_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='title',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='discussion',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_discussion_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='articles.discussion'),
        ),
    ]
