# Generated by Django 5.0.7 on 2024-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_title_discussion_topic_discussion_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
