# Generated by Django 5.0.7 on 2024-08-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_alter_article_article_link"),
        ("communities", "0009_communityarticle_assigned_moderator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="community_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.communityarticle",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("reviewer", "Reviewer Review"),
                    ("moderator", "Moderator Decision"),
                    ("public", "Public Review"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
