# Generated by Django 5.1.4 on 2025-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepdf',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepdf',
            name='pdf_file_url',
            field=models.FileField(blank=True, null=True, upload_to='article_pdfs/'),
        ),
    ]
