# Generated by Django 5.1.4 on 2025-03-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_articlepdf_external_url_and_more'),
        ('communities', '0011_community_community_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousidentity',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AddField(
            model_name='anonymousidentity',
            name='identicon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
