# Generated by Django 5.1.4 on 2025-03-17 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_reviewcommentrating'),
        ('communities', '0011_community_community_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anonymousidentity',
            unique_together={('user', 'article', 'community')},
        ),
    ]
