# Generated by Django 5.1.4 on 2025-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_anonymousidentity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_pseudonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_pseudonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='is_pseudonymous',
            field=models.BooleanField(default=False),
        ),
    ]
