# Generated by Django 5.1.4 on 2025-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_discussion_is_pseudonymous_review_is_pseudonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='is_pseudonymous',
            field=models.BooleanField(default=False),
        ),
    ]
