# Generated by Django 5.1.4 on 2025-04-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_discussioncomment_is_pseudonymous'),
        ('communities', '0013_rename_is_psuedonymous_communityarticle_is_pseudonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['submitter', 'created_at'], name='articles_ar_submitt_3d3489_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['article', 'created_at'], name='articles_re_article_0aed87_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['community', 'article'], name='articles_re_communi_d503d7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'article'], name='articles_re_user_id_31c15a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['community_article'], name='articles_re_communi_b4fe20_idx'),
        ),
    ]
