# Generated by Django 5.1.4 on 2025-05-10 21:51

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_article_article_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.Article.get_upload_path),
        ),
        migrations.AlterField(
            model_name='articlepdf',
            name='pdf_file_url',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.ArticlePDF.get_pdf_upload_path),
        ),
    ]
