# Generated by Django 5.2.3 on 2025-07-06 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0027_alter_article_article_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["submission_type"], name="articles_ar_submiss_9a6b3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["submission_type", "created_at"],
                name="articles_ar_submiss_014e7e_idx",
            ),
        ),
    ]
