# Generated by Django 5.2.3 on 2025-10-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0028_article_articles_ar_submiss_9a6b3f_idx_and_more"),
        ("communities", "0016_alter_community_banner_pic_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discussioncomment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DiscussionSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_subscribers",
                        to="articles.article",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_subscribers",
                        to="communities.community",
                    ),
                ),
                (
                    "community_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_subscribers",
                        to="communities.communityarticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="articles_di_user_id_dc82e2_idx",
                    ),
                    models.Index(
                        fields=["community_article", "is_active"],
                        name="articles_di_communi_c29426_idx",
                    ),
                    models.Index(
                        fields=["community", "is_active"],
                        name="articles_di_communi_61c1a8_idx",
                    ),
                    models.Index(
                        fields=["article", "is_active"],
                        name="articles_di_article_a76e6e_idx",
                    ),
                ],
                "unique_together": {("user", "community_article", "community")},
            },
        ),
    ]
