# Generated by Django 5.2.3 on 2026-01-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0030_discussionsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
