# Generated by Django 5.2.3 on 2026-02-12 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0031_discussion_is_resolved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(choices=[("unread", "Unread")], max_length=50),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("comment", "Comment"),
                            ("notification", "Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "flag_type"], name="userflag_user_flag"
                    ),
                    models.Index(
                        fields=["user", "flag_type", "entity_type"],
                        name="userflag_user_flag_etype",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="userflag_entity"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "flag_type", "entity_type", "entity_id"),
                        name="userflag_unique",
                    )
                ],
            },
        ),
    ]
