# Generated by Django 5.2.3 on 2026-02-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0032_userflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userflag",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("discussion", "discussion"),
                    ("comment", "comment"),
                    ("notification", "notification"),
                    ("review", "review"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userflag",
            name="flag_type",
            field=models.CharField(
                choices=[("unread", "unread"), ("pinned", "pinned")], max_length=50
            ),
        ),
    ]
