# Generated by Django 5.2.12 on 2026-03-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0033_alter_userflag_entity_type_alter_userflag_flag_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flag_type", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "articles_entityflag",
            },
        ),
        migrations.DeleteModel(
            name="UserFlag",
        ),
        migrations.AddIndex(
            model_name="entityflag",
            index=models.Index(fields=["user", "flag_type"], name="entityflag_user_flag"),
        ),
        migrations.AddIndex(
            model_name="entityflag",
            index=models.Index(fields=["user", "flag_type", "entity_type"], name="entityflag_user_flag_etype"),
        ),
        migrations.AddIndex(
            model_name="entityflag",
            index=models.Index(fields=["entity_type", "entity_id"], name="entityflag_entity"),
        ),
        migrations.AddIndex(
            model_name="entityflag",
            index=models.Index(
                condition=models.Q(("user__isnull", True)),
                fields=["flag_type", "entity_type", "entity_id"],
                name="entityflag_global_flag",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "flag_type", "entity_type", "entity_id"),
                name="entityflag_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("flag_type", "entity_type", "entity_id"),
                name="entityflag_unique_global",
            ),
        ),
    ]
