# Generated by Codex on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0034_entityflag_delete_userflag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="arxiv_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="canonical_url",
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="doi",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="pmid",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
