# Generated by Django 4.1 on 2024-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('published', 'published'), ('in review', 'in review'), ('rejected', 'rejected'), ('rejected by user', 'rejected by user'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('approved', 'approved'), ('pending', 'pending')], max_length=10),
        ),
    ]
