# Generated by Django 4.1 on 2024-06-06 18:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecommunity',
            name='accepted_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='privatecommunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatecommunity',
            name='discarded_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='privatecommunity',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatecommunity',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatecommunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('published', 'published'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('in review', 'in review'), ('rejected by user', 'rejected by user')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='privatecommunity',
            table='private_communities',
        ),
    ]
