# Generated by Django 4.1 on 2024-04-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_email_token_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('in review', 'in review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('published', 'published'), ('rejected by user', 'rejected by user'), ('submitted', 'submitted')], max_length=255),
        ),
    ]
