# Generated by Django 4.1 on 2024-04-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_communitymeta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('rejected by user', 'rejected by user'), ('published', 'published'), ('in review', 'in review'), ('submitted', 'submitted')], max_length=255),
        ),
    ]
