# Generated by Django 4.1 on 2024-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_communitymeta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('published', 'published'), ('rejected', 'rejected'), ('in review', 'in review'), ('rejected by user', 'rejected by user')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=10),
        ),
    ]
