# Generated by Django 5.0.3 on 2024-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Community_name", models.CharField(max_length=300, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("website", models.CharField(max_length=300, null=True)),
            ],
            options={
                "db_table": "community",
            },
        ),
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_reviewer", models.BooleanField(default=False)),
                ("is_moderator", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "community_member",
            },
        ),
        migrations.CreateModel(
            name="CommunityMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rejected", "rejected"),
                            ("submitted", "submitted"),
                            ("published", "published"),
                            ("rejected by user", "rejected by user"),
                            ("accepted", "accepted"),
                            ("in review", "in review"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "community_meta",
            },
        ),
        migrations.CreateModel(
            name="CommunityRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.CharField(max_length=5000, null=True)),
                ("summary", models.CharField(max_length=5000, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rejected", "rejected"),
                            ("pending", "pending"),
                            ("approved", "approved"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "community_request",
            },
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "moderator",
            },
        ),
        migrations.CreateModel(
            name="OfficialReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Official_Reviewer_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "officialreviewer",
            },
        ),
        migrations.CreateModel(
            name="UnregisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "unregistered_user",
            },
        ),
    ]
