# Generated by Django 5.0.3 on 2024-03-27 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("article_name", models.CharField(max_length=300, unique=True)),
                (
                    "article_file",
                    models.FileField(blank=True, null=True, upload_to="articles_file/"),
                ),
                ("Public_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("keywords", models.TextField()),
                ("authorstring", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("license", models.CharField(max_length=255, null=True)),
                (
                    "published_article_file",
                    models.FileField(
                        blank=True, null=True, upload_to="published_article_file/"
                    ),
                ),
                ("published", models.CharField(max_length=255, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("Code", models.CharField(blank=True, max_length=100, null=True)),
                ("Abstract", models.TextField(blank=True, max_length=5000, null=True)),
                ("views", models.IntegerField(default=0)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "article",
            },
        ),
        migrations.CreateModel(
            name="ArticleBlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "article_blocked_user",
            },
        ),
        migrations.CreateModel(
            name="ArticleModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "article_moderator",
            },
        ),
        migrations.CreateModel(
            name="ArticleReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "article_reviewer",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="CommentBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comment", models.TextField(max_length=20000)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("Comment_date", models.DateTimeField(auto_now_add=True)),
                ("tag", models.CharField(default="public", max_length=255)),
                (
                    "comment_type",
                    models.CharField(default="publiccomment", max_length=255),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("decision", "Decision"),
                            ("comment", "Comment"),
                        ],
                        default="comment",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "comment_base",
            },
        ),
        migrations.CreateModel(
            name="HandlersBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "handler_base",
            },
        ),
        migrations.CreateModel(
            name="LikeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "like_base",
            },
        ),
    ]
