# Generated by Django 5.0.3 on 2024-03-27 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("article", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="community",
            field=models.ManyToManyField(
                through="community.CommunityMeta", to="community.community"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="parent_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="articleblockeduser",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Article",
                to="article.article",
            ),
        ),
    ]
