# Generated by Django 5.0.3 on 2024-03-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("article", "0002_initial"),
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articleblockeduser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="blocked_users",
            field=models.ManyToManyField(
                through="article.ArticleBlockedUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="articlemoderator",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="article.article"
            ),
        ),
        migrations.AddField(
            model_name="articlemoderator",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.moderator"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="moderator",
            field=models.ManyToManyField(
                related_name="article_moderators",
                through="article.ArticleModerator",
                to="community.moderator",
            ),
        ),
        migrations.AddField(
            model_name="articlereviewer",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="article.article"
            ),
        ),
        migrations.AddField(
            model_name="articlereviewer",
            name="officialreviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="community.officialreviewer",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reviewer",
            field=models.ManyToManyField(
                related_name="article_reviewers",
                through="article.ArticleReviewer",
                to="community.officialreviewer",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="article.article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                related_name="article_authors",
                through="article.Author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentbase",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commentbase",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="article.article"
            ),
        ),
        migrations.AddField(
            model_name="commentbase",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="article.commentbase",
            ),
        ),
        migrations.AddField(
            model_name="commentbase",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="article.commentbase",
            ),
        ),
        migrations.AddField(
            model_name="handlersbase",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="handlersbase",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="article.article"
            ),
        ),
        migrations.AddField(
            model_name="likebase",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="article.commentbase",
            ),
        ),
        migrations.AddField(
            model_name="likebase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("article", "User")},
        ),
        migrations.AlterUniqueTogether(
            name="handlersbase",
            unique_together={("User", "handle_name", "article")},
        ),
    ]
