# Generated by Django 5.2.12 on 2026-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdeviceauth',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
