"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config

from myapp.constants import FIFTEEN_MINUTES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ENVIRONMENT = config("ENVIRONMENT", default="local")

ALLOWED_HOSTS = [
    "scicommons.org",
    "test.scicommons.org",
    "alphatest.scicommons.org",
    "backend.scicommons.org",
    "backendtest.scicommons.org",
    "localhost",
    "127.0.0.1",
]

# Allow all hosts in debug mode for development
if DEBUG:
    ALLOWED_HOSTS.append("*")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "ninja",
    "users",
    "communities",
    "articles",
    "integrations",
    "posts",
    # Added by Claude on 2026-08-10: per-user feed preferences (see feeds/models.py).
    "feeds",
    "storages",
    "channels",
]

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
    "ninja.compatibility.files.fix_request_files_middleware",
    "myapp.middleware.RequestTimingMiddleware",
]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://scicommons.org",
    "https://test.scicommons.org",
    "https://alphatest.scicommons.org",
    "https://backend.scicommons.org",
    "https://backendtest.scicommons.org",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

EXTENSION_CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config("EXTENSION_CORS_ALLOWED_ORIGINS", default="").split(",")
    if origin.strip()
]
INTEGRATION_CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config("INTEGRATION_CORS_ALLOWED_ORIGINS", default="").split(",")
    if origin.strip()
]
CORS_ALLOWED_ORIGINS += EXTENSION_CORS_ALLOWED_ORIGINS + INTEGRATION_CORS_ALLOWED_ORIGINS

# `^chrome-extension://[a-p]{32}$` matches EVERY Chrome extension ID, so with
# CORS_ALLOW_CREDENTIALS=True and `authorization` in CORS_ALLOW_HEADERS it lets any extension a
# user has installed make credentialed calls to the whole API. Keep it only as a development
# convenience: once either origins list pins the real origins, drop the regex.
if EXTENSION_CORS_ALLOWED_ORIGINS or INTEGRATION_CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGIN_REGEXES = []
else:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^chrome-extension://[a-p]{32}$",
    ]

# Registered extension clients. `client_id` is caller-supplied, so it has to be checked
# against this list rather than merely echoed back at token exchange.
EXTENSION_ALLOWED_CLIENT_IDS = [
    client_id.strip()
    for client_id in config("EXTENSION_ALLOWED_CLIENT_IDS", default="scicommons-clipper").split(",")
    if client_id.strip()
]

# Exact redirect URIs. When set, these are the only redirects accepted -- no implicit trust
# of arbitrary chrome-extension:// or *.chromiumapp.org URIs.
EXTENSION_ALLOWED_REDIRECT_URIS = [
    uri.strip() for uri in config("EXTENSION_ALLOWED_REDIRECT_URIS", default="").split(",") if uri.strip()
]

EXTENSION_ALLOWED_REDIRECT_URI_PREFIXES = [
    prefix.strip()
    for prefix in config("EXTENSION_ALLOWED_REDIRECT_URI_PREFIXES", default="").split(",")
    if prefix.strip()
]
EXTENSION_AUTH_CODE_TTL_SECONDS = config("EXTENSION_AUTH_CODE_TTL_SECONDS", default=300, cast=int)

# The generalised integrations layer (#168) reads INTEGRATION_*, while the extension work
# (#167) shipped EXTENSION_*. Default each new name to the corresponding extension value so a
# deployment that has already set the EXTENSION_* env vars keeps working untouched.
INTEGRATION_AUTH_CODE_TTL_SECONDS = config(
    "INTEGRATION_AUTH_CODE_TTL_SECONDS", default=EXTENSION_AUTH_CODE_TTL_SECONDS, cast=int
)
INTEGRATION_DEVICE_CODE_TTL_SECONDS = config("INTEGRATION_DEVICE_CODE_TTL_SECONDS", default=900, cast=int)
INTEGRATION_DEVICE_POLL_INTERVAL_SECONDS = config("INTEGRATION_DEVICE_POLL_INTERVAL_SECONDS", default=5, cast=int)

# Registered integration clients. `client_id` arrives from the caller, so it has to be checked
# against a registry rather than trusted or compared only to itself.
INTEGRATION_ALLOWED_CLIENT_IDS = [
    client_id.strip()
    for client_id in config(
        "INTEGRATION_ALLOWED_CLIENT_IDS", default="scicommons-zotero,scicommons-clipper"
    ).split(",")
    if client_id.strip()
]
# Union with the extension list so a deployment that registered extra clients via
# EXTENSION_ALLOWED_CLIENT_IDS does not lose them when the integrations layer takes over.
INTEGRATION_ALLOWED_CLIENT_IDS += [
    client_id for client_id in EXTENSION_ALLOWED_CLIENT_IDS if client_id not in INTEGRATION_ALLOWED_CLIENT_IDS
]

# Exact redirect URIs. When set, these are the only ones accepted -- no implicit trust of
# arbitrary chrome-extension:// or *.chromiumapp.org URIs.
INTEGRATION_ALLOWED_REDIRECT_URIS = [
    uri.strip() for uri in config("INTEGRATION_ALLOWED_REDIRECT_URIS", default="").split(",") if uri.strip()
] or EXTENSION_ALLOWED_REDIRECT_URIS

INTEGRATION_ALLOWED_REDIRECT_URI_PREFIXES = [
    prefix.strip()
    for prefix in config("INTEGRATION_ALLOWED_REDIRECT_URI_PREFIXES", default="").split(",")
    if prefix.strip()
] or EXTENSION_ALLOWED_REDIRECT_URI_PREFIXES

# CORS Additional Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Security Settings
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Additional Security Headers
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = "require-corp"

ROOT_URLCONF = "myapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "myapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="myapp"),
        "USER": config("DB_USER", default="myapp"),
        "PASSWORD": config("DB_PASSWORD", default="myapp"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

if not DEBUG:
    DATABASES["default"] = dj_database_url.parse(config("DATABASE_URL"))


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

FRONTEND_URL = config("FRONTEND_URL")

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# MEDIA_URL = "/media/"

# Arbutus Object Storage Configuration (S3-compatible)
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = config(
    "AWS_S3_ENDPOINT_URL", default="https://object-arbutus.alliancecan.ca"
)
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="")  # Arbutus doesn't require region
AWS_S3_CUSTOM_DOMAIN = config(
    "AWS_S3_CUSTOM_DOMAIN",
    default=(
        "object-arbutus.alliancecan.ca/"
        "56ef6dfb16b64243bb362f8bb7a23da2:cdn.scicommons.org"
    ),
)
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = "s3"  # Required for Arbutus Object Storage
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True  # Verify SSL certificates
AWS_S3_ADDRESSING_STYLE = "path"  # Use path-style addressing for compatibility

# Object Parameters - Cache and Content Type settings
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",  # Cache for 24 hours
}

# Default ACL for uploaded files (public-read for CDN access)
AWS_DEFAULT_ACL = config("AWS_DEFAULT_ACL", default="public-read")

# Querystring Auth - Set to False if files should be publicly accessible
AWS_QUERYSTRING_AUTH = config("AWS_QUERYSTRING_AUTH", default=False, cast=bool)


STORAGES = {
    # Media File (PDFs, images, etc.) Management
    "default": {
        "BACKEND": "myapp.storage.ArbutusMediaStorage",
    },
    "staticfiles": {
        # use default storage for static files
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
        # "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        # "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": ("django.contrib.auth.password_validation." "UserAttributeSimilarityValidator"),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery Configurations
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
print("redis: ", CELERY_BROKER_URL, CELERY_RESULT_BACKEND)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_CONCURRENCY = 5

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_HOST_URL", default="redis://localhost:6379/1"),  # Use DB 1 for Django cache
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PARSER_CLASS": "redis.connection.HiredisParser",
            "SOCKET_CONNECT_TIMEOUT": 5,  # seconds
            "SOCKET_TIMEOUT": 5,  # seconds
        },
        "KEY_PREFIX": "sci:",  # Optional, helps prevent key collisions
        "TIMEOUT": FIFTEEN_MINUTES,  # Default cache timeout (5 minutes)
    }
}

# Optional: Use cache for session storage
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# -------------------- Logging Configuration --------------------
LOG_FORMAT = "[%(levelname)s] - %(asctime)s - %(name)s - %(message)s"

if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "detailed": {
                "format": LOG_FORMAT,
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "detailed",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "loggers": {
            "django.db.backends": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "myapp.middleware": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
else:
    # Ensure /logs directory (mounted from host) exists inside container
    LOG_DIR = Path(config("LOG_DIR", default="/logs"))
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE_PATH = LOG_DIR / f"{ENVIRONMENT}.log"
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "detailed": {
                "format": LOG_FORMAT,
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "detailed",
                "level": "INFO",
            },
            "error_file": {
                "class": "logging.FileHandler",
                "filename": str(LOG_FILE_PATH),
                "formatter": "detailed",
                "level": "ERROR",
            },
        },
        "root": {
            "handlers": ["console", "error_file"],
            "level": "INFO",
        },
    }
# ---------------------------------------------------------------

# ASGI application
ASGI_APPLICATION = "myapp.asgi.application"

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config("REDIS_HOST_URL", default="redis://localhost:6379/2")],  # Use DB 2 for channels
        },
    },
}

# Update CORS settings to allow WebSocket connections
CORS_ALLOW_WEBSOCKETS = True
